environment:

  matrix:

    - PYTHON: "C:\\Miniconda37-x64"
      PYTHON_VERSION: "3.7"
      DEPS: "numpy scipy!=1.5.0 matplotlib pillow pandas scikit-image pyyaml pytables numba scikit-learn"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION%"

install:
  # Prepend to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%CONDA_ROOT%\\Library\\bin;%PATH%"

  # Install dependencies
  - conda update --yes conda
  - conda create -n testenv --yes %DEPS% python=%PYTHON_VERSION%
  - activate testenv

  # for debugging...
  - "ECHO %PATH%"
  - python --version
  - conda info
  - conda list

build: false

test_script:
  - python -munittest
