environment:

  matrix:

    # "Legacy" environments: oldest supported versions, without and with numba

    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7"
      DEPS: "numpy=1.8.2 scipy=0.14.0 matplotlib=1.3 pillow=2.1 pandas=0.13.0 scikit-image=0.9 pytables scikit-learn=0.14.1 pyyaml pims=0.4.1"

    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7"
      DEPS: "numpy=1.8.2 scipy=0.14.0 matplotlib=1.3 pillow=2.1 pandas=0.13.0 scikit-image=0.9 numba=0.13.4 pytables scikit-learn=0.14.1 pyyaml pims=0.4.1"

    # "Typical" environments: package versions from 2016

    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      DEPS: "numpy=1.10 scipy=0.17 matplotlib=1.5 pillow=3.1 pandas=0.18.1 scikit-image=0.12 pytables numba=0.23.1 scikit-learn=0.17.1 pyyaml pims=0.4.1"

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_VERSION: "3.5"
      DEPS: "numpy=1.10 scipy=0.17 matplotlib=1.5 pillow=3.1 pandas=0.18.1 scikit-image=0.12 pytables numba=0.23.1 scikit-learn=0.17.1 pyyaml pims=0.4.1"

    # Environments with most recent versions, on python 2.7 and python 3.6

    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      DEPS: "numpy scipy matplotlib pillow pandas scikit-image pyyaml pytables numba scikit-learn pims"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      DEPS: "numpy scipy matplotlib pillow pandas scikit-image pyyaml pytables numba scikit-learn pims"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION%"

install:
  # Prepend to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%CONDA_ROOT%\\Library\\bin;%PATH%"

  # Install dependencies
  - conda update --yes conda
  - conda config --append channels conda-forge
  - conda create -n testenv --yes %DEPS% pip nose setuptools python=%PYTHON_VERSION%
  - activate testenv

  # for debugging...
  - "ECHO %PATH%"
  - "python --version"
  - conda info
  - conda list

build: false

before_test:
  - "%CMD_IN_ENV% python setup.py install"

test_script:
  - "%CMD_IN_ENV% nosetests --nologcapture -a '!slow'"
