environment:

  matrix:

    - PYTHON: "C:\\Miniconda"
      PYTHON_VERSION: "2.7"
      DEPS: "numpy=1.8.2 scipy=0.14.0 matplotlib=1.3 pillow=2.1 pandas=0.13.0 scikit-image=0.9 numba=0.13.4 pytables scikit-learn=0.14.1 pyyaml"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      DEPS: "numpy scipy matplotlib pillow pandas scikit-image pyyaml pytables numba scikit-learn"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION%"

install:
  # Prepend to the PATH of this build
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%CONDA_ROOT%\\Library\\bin;%PATH%"

  # Install dependencies
  - conda update --yes conda
  - conda create -n testenv --yes %DEPS% nose python=%PYTHON_VERSION%
  - activate testenv

  # for debugging...
  - "ECHO %PATH%"
  - python --version
  - conda info
  - conda list

build: false

test_script:
  - nosetests --nologcapture -A "not slow"
