NOTEBOOK_DIR = ../../../trackpy-examples/notebooks
notebooks:

	ipython nbconvert --to rst $(NOTEBOOK_DIR)/walkthrough.ipynb
	ipython nbconvert --to rst $(NOTEBOOK_DIR)/on-disk.ipynb
	ipython nbconvert --to rst $(NOTEBOOK_DIR)/prediction.ipynb
	ipython nbconvert --to rst $(NOTEBOOK_DIR)/uncertainty.ipynb
	ipython nbconvert --to rst $(NOTEBOOK_DIR)/performance.ipynb
	ipython nbconvert --to rst $(NOTEBOOK_DIR)/parallel-locate.ipynb
	ipython nbconvert --to rst $(NOTEBOOK_DIR)/custom-feature-detection.ipynb
