name: Pip

on: [push, pull_request, workflow_dispatch]

jobs:
  TestLinux:
    name: Python ${{ matrix.python }} ${{ matrix.display_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: "3.8"
            display_name: "2019"
            deps: "numpy==1.18.* scipy==1.4.* matplotlib==3.1.* pandas==1.0.* tables==3.6.* scikit-learn==0.22.* pyyaml numba==0.47.* llvmlite==0.31.* looseversion>=1.0.1"
          - python: "3.9"
            display_name: "2020"
            deps: "numpy==1.19.* scipy==1.5.* matplotlib==3.3.* pandas==1.1.* tables==3.6.* scikit-learn==0.24.* pyyaml numba==0.53.* llvmlite==0.36.* looseversion>=1.0.1"
          - python: "3.10"
            display_name: "2021"
            deps: "numpy==1.22.* scipy==1.7.* matplotlib==3.5.* pandas==1.3.* tables==3.6.* scikit-learn==1.0.* pyyaml numba==0.55.* llvmlite==0.38.* looseversion>=1.0.1"
          - python: "3.11"
            display_name: "2022"
            deps: "numpy==1.25.* scipy==1.9.* matplotlib==3.6.* pandas==1.4.* tables==3.8.* scikit-learn==1.1.* pyyaml numba==0.57.* llvmlite==0.40.* looseversion"
          # most recent
          - python: '3.x'
            display_name: "latest, no optional deps"
            deps: "numpy scipy matplotlib pandas pyyaml looseversion"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install HDF5 library
        run: sudo apt-get install libhdf5-dev

      - name: Install python dependencies
        shell: bash
        run: |
          pip install --disable-pip-version-check --upgrade pip wheel
          pip install --no-build-isolation pytest ${{ matrix.numpy }};
          pip install --no-build-isolation ${{ matrix.deps }};
          pip list

      - name: Run tests
        shell: bash
        run: |
          pytest trackpy
