name: Pip

on: [push, pull_request]

jobs:
  TestLinux:
    name: Python ${{ matrix.python }} ${{ matrix.display_name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # 2017
          - python: 3.6
            display_name: "2017"
            numpy: "numpy==1.14.*"  # pre-install numpy due to issue in numba 0.32 wheel building
            deps: "scipy==1.1.* matplotlib==2.1.* pillow==4.3.* pandas==0.22.* tables==3.4.* scikit-learn==0.19.* pyyaml numba==0.32.* llvmlite==0.17.*"
          # 2018
          - python: 3.7
            display_name: "2018"
            deps: "numpy==1.16.* scipy==1.3.* matplotlib==2.2.* pandas==0.23.* tables==3.5.* scikit-learn==0.20.* pyyaml numba==0.45.* llvmlite==0.29.*"
          # 2019
          - python: 3.8
            display_name: "2019"
            deps: "numpy==1.18.* scipy==1.4.* matplotlib==3.1.* pandas==0.25.* tables==3.6.* scikit-learn==0.22.* pyyaml numba==0.47.* llvmlite==0.31.*"
          # 2020
          - python: 3.9
            display_name: "2020"
            deps: "numpy==1.19.* scipy==1.5.* matplotlib==3.3.* pandas==1.1.* tables==3.6.* scikit-learn==0.24.* pyyaml numba==0.53.* llvmlite==0.36.*"
          # 2021 (use Py3.9 & numpy==1.20 due to numba compatibility)
          - python: 3.9
            display_name: "2021"
            deps: "numpy==1.20.* scipy==1.7.* matplotlib==3.5.* pandas==1.3.* tables==3.6.* scikit-learn==1.0.* pyyaml numba==0.54.* llvmlite==0.37.*"
          # most recent
          - python: '3.x'
            display_name: "latest, no optional deps"
            deps: "numpy scipy matplotlib pandas pyyaml"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install HDF5 library
        run: sudo apt-get install libhdf5-dev

      - name: Install python dependencies
        shell: bash
        run: |
          pip install --disable-pip-version-check --upgrade pip wheel
          pip install --no-build-isolation pytest ${{ matrix.numpy }};
          pip install --no-build-isolation ${{ matrix.deps }};
          pip list

      - name: Run tests
        shell: bash
        run: |
          pytest trackpy
